name: Go
on: [push]
jobs:
  container-job:
    runs-on: ubuntu-latest

    container:
      image: golang-1.13.3-alpine3.10

    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_pass
          POSTGRES_DB: postgres_db
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v1

    - name: Download module dependencies
      env: 
         GOPROXY: "https://proxy.golang.org"
      run: go mod download

    - name: Build
      run: go build .

    - name: Test
      run: go test -v .
